### PR TITLE
Add clang builds again

### PR DESCRIPTION
**Pull request by AndreVuillemot160**
https://github.com/AfoninZ/MultiMC5-Cracked/pull/42 same pull request

### CODE REVIEW

**Comment by AndreVuillemot160** [comment]
Added Mac OS ci

**Comment by AndreVuillemot160** [comment]
?

**Comment by Sebastian-byte** [comment]
This PR isn't really necessary, the original MultiMC don't use Clang in their CI, but thanks anyway.

**Comment by AndreVuillemot160** [comment]
well okie

**Pull request closed without merging**
