### PR TITLE
Automated macOS builds

### PR DESCRIPTION
**Pull request by AfoninZ**
Work in progress. Commits will be squashed when it will actually work

### CODE REVIEW

**Comment by Sebastian-byte** [comment]
Ok, I've done some improvements and now macOS build uses cache, builds faster, and is consistent with the other builds.

**Comment by Sebastian-byte** [comment]
Ok, I've done some improvements and now macOS build uses cache, builds faster (only takes 10 minutes, even less than Windows build), and is consistent with the other builds.

**Comment by AfoninZ** [comment]
Don't know if it's a bug on my side, but for now I need to `chmod +x` the `Contents/MacOS/MultiMC` file in order to make the bundle runnable - maybe that can be added to the install step.

Also a minor issue, but it seems like the macOS build of MultiMC uses some Classic-style theme instead of a Mac-like theme that vanilla MultiMC uses. Maybe that's because of a different Qt version. Anyway, thanks a lot for improving the build tasks - I'm not really experienced with CI so my task was pretty bad.

**Comment by Sebastian-byte** [comment]
Yes, you do, that also happens in Linux build, we should chmod +x MultiMC before packaging it.

**Comment by Sebastian-byte** [comment]
About the Qt version, we should consider using the same version.

**Comment by AfoninZ** [comment]
MultiMC mentions Qt 5.6+ in its build instructions, and I suspect Mac builds use some old version of Qt, maybe 5.6. However, MultiMC devs themselves considered upgrading to a newer Qt version in the future.

**Comment by Sebastian-byte** [comment]
Yes, however that same error happened in Windows first build, since you used Qt 5.15.2 there, maybe the Qt version is too new?

**Comment by AfoninZ** [comment]
can't figure out where the file to be chmodded actually is

**Comment by Sebastian-byte** [comment]
Do you really need to chmod the 2 files? You think you only need to chmod the first one.

**Comment by AfoninZ** [comment]
Hmm, you're right. It's just I've lost one of the files back when we were manually compiling MMC, so instead I chmodded the second one and started MMC from there. Honestly don't know if this should be fixed or be left as-is.

**Comment by AndreVuillemot160** [comment]
Wow, it seems building fr

**Comment by AndreVuillemot160** [comment]
Hooray, Mac Os build has been built

**Comment by Sebastian-byte** [comment]
> Hmm, you're right. It's just I've lost one of the files back when we were manually compiling MMC, so instead I chmodded the second one and started MMC from there. Honestly don't know if this should be fixed or be left as-is.

We should check if the second file is also chmodded in vanilla MMC.

**Comment by Sebastian-byte** [comment]
> Hooray, Mac Os build has been built

I'm still surprised how macOS build is faster than Windows one 😲

**Comment by AndreVuillemot160** [comment]
Can

> > Hooray, Mac Os build has been built
> 
> I'm still surprised how macOS build is faster than Windows one 😲

Conspiracy theory time.
Hardware? Not sure about it since it is VM.

**Comment by AfoninZ** [comment]
> We should check if the second file is also chmodded in vanilla MMC.
From what I see, both files are indeed chmodded in a vanilla Linux build.

**Comment by Sebastian-byte** [comment]
> From what I see, both files are indeed chmodded in a vanilla Linux build.

Ok so we can left it as-is.

**Comment by AfoninZ** [comment]
Ideally we need to build a Universal bundle before merging this branch. The problem is, currently MMC runs as an Intel app, therefore using Intel builds of native libraries and probably requiring an Intel build of Java. Relying on Rosetta is not sustainable, so I'm for compiling an ARM build and lipo'ing it with the Intel one so we can ship a Universal bundle.

**Comment by Sebastian-byte** [comment]
> Ideally we need to build a Universal bundle before merging this branch. The problem is, currently MMC runs as an Intel app, therefore using Intel builds of native libraries and probably requiring an Intel build of Java. Relying on Rosetta is not sustainable, so I'm for compiling an ARM build and lipo'ing it with the Intel one so we can ship a Universal bundle.

Vanilla MMC currently doesn't support ARM, and so we shouldn't, currently vanilla developers are experimenting with a M1 build, but not more than that, a experiment.

**Comment by AfoninZ** [comment]
Ok, maybe this fork should indeed stay just a fork with minimal features added. As for now I'll try https://github.com/yusefnapora/m1-multimc-hack and report back if it works nicely.

**Comment by Sebastian-byte** [comment]
> UPD: Can confirm it mostly works. Should we link this repo as an instruction for M1 Macs in README and merge this branch then? Or we still need to downgrade Qt down to 5.6 and stay on it until MMC developers do an upgrade?

We should link it, and I think we must downgrade to the Qt version used in the vanilla build, so we can get a "normal" style, instead of a classic one.

**Comment by AfoninZ** [comment]
I understand why we want to be as close to upstream as possible - minimal maintenance and minimal bugs introduced to the launcher. Yeah, I think for now we should downgrade to 5.6 instead of fixing anything.

Maybe if we ever implement a fix for theming in newer Qt versions we should try to promote it to upstream MMC (obviously, from a repo not related to any kind of "cracked" MMC). But that's for the future.

**Comment by Sebastian-byte** [comment]
> Maybe if we ever implement a fix for theming in newer Qt versions we should try to promote it to upstream MMC (obviously, from a repo not related to any kind of "cracked" MMC). But that's for the future.

Yes, maybe.

**Comment by Sebastian-byte** [comment]
Yes, we could build it manually as explained in https://doc.qt.io/archives/qt-5.6/osx-building.html

**Comment by Sebastian-byte** [comment]
Seems like getting Qt5.6 in macOS is impossible currently.

**Comment by Sebastian-byte** [comment]
lgtm

**Comment by Sebastian-byte** [comment]
LGTM

**Pull request merged**
