### PR TITLE
Update launcher icon

### PR DESCRIPTION
**Pull request by imabhaysutar**
I have managed to make decent looking icons for the project : )

This is how it looks.
Screenshot 2021-11-20 at 3 19 17 PM

### CODE REVIEW

**Comment by imabhaysutar** [comment]
Actually its not blurred, it asks for 16-128, which it is.

**Comment by Samisafool** [comment]
The icns is 64x64, it could be 128x128 right?

**Comment by Samisafool** [comment]
the .ico is 256x256 and it actually looks fine.

**Comment by imabhaysutar** [comment]
yes it is, is this fine for now?

**Comment by Samisafool** [comment]
Yes, but just remove the png

**Comment by Sebastian-byte** [comment]
LGTM, thanks for your submission!

**Comment by Sebastian-byte** [comment]
Also, the CI is failing due to one problem in our end, don't worry.

**Pull request merged**
