### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Samisafool**
The launcher builds successfully if you also merge #130

### CODE REVIEW

**Comment by Sebastian-byte** [comment]
Please don't change the Java version used, keep it the same as vanilla

**Comment by Samisafool** [comment]
What? I'm pretty sure it doesn't matter what version vanilla uses here. It just changes a few things so the launcher can build if you have java 17. I can lower the requirement if you like, you could've just requested changes.

**Comment by Sebastian-byte** [comment]
> What? I'm pretty sure it doesn't matter what version vanilla uses here. It just changes a few things so the launcher can build if you have java 17. I can lower the requirement if you like, you could've just requested changes.

I mean that I want to keep the Java version used to build exactly the same as in the upstream, because this might cause unwanted problems and conflicts, also remember that this is a light fork, also about the build fix, I'm waiting to see if TeamCity guest authentication gets re-enabled, if not, will remove the build number.

**Comment by Samisafool** [comment]
Okay, so there's a PR on MultiMC to change this version to java 7.

If I revert the changes here, I suppose it will build anyway?

**Comment by Samisafool** [comment]
Also the build number line is commented out, not removed.

**Comment by Samisafool** [comment]
@Sebastian-byte 

````
   47.539 D Getting access token.
   47.539 D Finished reading authentication response.
   47.539 D Task "Yggdrasil(0x55d93386bd60)" succeeded
   47.539 D AuthFlow: "Fetching the Minecraft profile."
   48.759 W AuthRequest::onRequestError: Error 204
   48.759 W AuthRequest::onRequestError: Error string:  "Host requires authentication"
   48.760 W AuthRequest::onRequestError: HTTP status 401 "Unauthorized"
   48.760 C Task "MojangLogin(0x55d93386a330)" failed:  "Minecraft Java profile acquisition failed."
````
Looks like local server is broken again.

**Comment by Samisafool** [comment]
Same with Ely.by

**Pull request closed without merging**
