### PR TITLE
Small build fix

### PR DESCRIPTION
**Pull request by Samisafool**
Build still fails, but idk

### CODE REVIEW

**Comment by Samisafool** [comment]
@Sebastian-byte would you have a look at this?

**Comment by Sebastian-byte** [comment]
> @Sebastian-byte would you have a look at this?

I believe it's better to wait for now.

**Comment by Samisafool** [comment]
Okay, well keep this open, I'll push some more stuff

**Comment by Samisafool** [comment]
@Sebastian-byte Should I revert the github workflow change that comments out the build version thing? Also I did a few things, if you wanna merge them feel free to.

**Comment by Sebastian-byte** [comment]
> @Sebastian-byte Should I revert the github workflow change that comments out the build version thing? Also I did a few things, if you wanna merge them feel free to.

Yes, consider reverting it.

**Comment by Samisafool** [comment]
> > @Sebastian-byte Should I revert the github workflow change that comments out the build version thing? Also I did a few things, if you wanna merge them feel free to.
> 
> Yes, consider reverting it.

Done

**Pull request closed without merging**
