### PR TITLE
Tweak the github workflows.

### PR DESCRIPTION
**Pull request by Samisafool**
- Removes unneccessary junk

- Removes line slowing down MacOS build

- Removes anallytics

- Temporarily removes the build version number, please readd it when multimc enables it. Can revert if you want.

Please squash the commits.

### CODE REVIEW

**Comment by Samisafool** [comment]
Also, currently fixed the build. Compiling rn.

**Comment by Samisafool** [comment]
It didn't fix, I don't have the time, going to sleep bye

**Comment by Sebastian-byte** [comment]
I consider that we should keep build just as the upstream, the flags are essentially how the upstream builds, but the build fixes are appreciated.

**Comment by Samisafool** [comment]
Actually, it's unnecessary to put those flags there because the Cmakelists.txt file already has them set.

**Pull request closed without merging**
