### PR TITLE
Add a bit of instructions in readme

### PR DESCRIPTION
**Pull request by AndreVuillemot160**
A lot of issues made by people asking how to use the launcher, and this PR adds a sort of instructions on how to use the launcher. Pretty simple.

### CODE REVIEW

**Comment by AndreVuillemot160** [comment]
https://github.com/AfoninZ/MultiMC5-Cracked/issues/69
https://github.com/AfoninZ/MultiMC5-Cracked/issues/65

**Comment by Samisaprogrammer** [comment]
there is a typo, Additional

**Comment by AndreVuillemot160** [comment]
done

**Comment by Sebastian-byte** [comment]
LGTM

**Pull request merged**
