### PR TITLE
Update commits and Windows download link

### PR DESCRIPTION
**Pull request by Sebastian-byte**

### CODE REVIEW

**Comment by Sebastian-byte** [comment]
@Panderine I updated the Windows download link.

**Comment by Panderine** [comment]
windows version doesn't launch

**Comment by Sebastian-byte** [comment]
huh, it works for me.
image

**Comment by Sebastian-byte** [comment]
Try using the old zlib1.dll file from the old build

**Comment by Panderine** [comment]
> huh, it works for me.
> 
> image

Tried downloading again and I get this error:

image

**Comment by Panderine** [comment]
> Try using the old zlib1.dll file from the old build

that did it. It works now

**Comment by Sebastian-byte** [comment]
Ohh probably due that I grab the zlib dll from an Windows 10 component, I will update the Download link with a fixed version

**Comment by AfoninZ** [comment]
Thanks to all of you guys. I really have no time to maintain this

**Comment by Sebastian-byte** [comment]
@AfoninZ No problem!, can you give me contributor permission so I can update the repo without waiting for your response?

**Comment by Dakkaron** [comment]
@AfoninZ This is a bit offtopic, but I don't have any other place to post this. If there are now a few more people helping out and maybe stuff like CI is to be made, where a bit more synchronization is required, would you mind opening up the "issues" section for this project? I'd maybe like to contribute the one or the other thing.

**Comment by Pepe424** [comment]
Hi developers! Can be can made function that will save your latest used username. So that I don't have to re-enter the name every time I run the game.
I really appreciate your work.
Happy Mac user.

**Comment by Panderine** [comment]
There is another fork of multimc5 that adds that already https://github.com/Ponywka/MultiMC5-with-offline

**Comment by AfoninZ** [comment]
@Dakkaron Sorry for disappearing from the internet again, I'm giving you contributor permissions ASAP

**Comment by Sebastian-byte** [comment]
No Problem! again, thank you!

**Comment by Sebastian-byte** [comment]
@AfoninZ Can you also give me contributor permissions?

**Comment by AfoninZ** [comment]
Invite sent, check your mailbox

By the way, I had no idea there is a better fork of MultiMC5 - it should have more way more stars than mine. I guess it is better to join the efforts and contribute any future features to https://github.com/Ponywka/MultiMC5-with-offline. Currently it lacks a Linux build (I guess I'll work on that on the weekend)

**Comment by Sebastian-byte** [comment]
@AfoninZ Yup!, Already accepted it, Ponywka modified the account system and uses the same generic token that your modified MultiMC uses, so are the same thing with an different implementation.

**Comment by Dakkaron** [comment]
Would be really useful to merge both forks. They do essentially the same thing the same way. No need for two groups of people to do the same thing.

**Pull request merged**
