### PR TITLE
Add Clang-based builds to Linux builds

### PR DESCRIPTION
**Pull request by AndreVuillemot160**
This PR adds Clang-based builds on GNU/Linux to the CI.

It's been tested that Clang have far more better performance than GCC and MSVC.
Links:
https://github.com/namazso/OpenHashTab/issues/34

Also, when merging this PR squash commits please.

### CODE REVIEW

**Comment by AndreVuillemot160** [comment]
Why so many commits? Originally I tried to add Windows Clang builds as well, but this is a big clusterfuck so I decided to abandon.

**Comment by Sebastian-byte** [comment]
Is inefficient to have two Linux builds, we could remove the GCC build.

**Comment by AfoninZ** [comment]
What kind of performance benefit does a clang build of the *launcher* make? Is there any difference with CPU, RAM usage and the game performance while running the game with the clang compile? If there are any differences for this specific usecase, please report them here. If the difference is present, I'm up to the change.

**Comment by Sebastian-byte** [comment]
> What kind of performance benefit does a clang build of the _launcher_ make? Is there any difference with CPU, RAM usage and the game performance while running the game with the clang compile? If there are any differences for this specific usecase, please report them here. If the difference is present, I'm up to the change.

It does improve build performance, but it shouldn't be a problem since Linux GCC build is already fast enough.

**Comment by AndreVuillemot160** [comment]
Fetched the new CI

**Comment by Sebastian-byte** [comment]
Seems like the clang linux build doesn't work in Ubuntu 18.04

**Comment by AndreVuillemot160** [comment]
> Seems like the clang linux build doesn't work in Ubuntu 18.04

Hm... I will try fix it.

**Comment by AndreVuillemot160** [comment]
Alright, fixed.

**Comment by AfoninZ** [comment]
Commits from upstream aren't exactly related to clang and stuff, we do that separately from other PRs. @Dakkaron @Sebastian-byte, could you please check this and advise the best practice to add these commits?

**Comment by Sebastian-byte** [comment]
I think is better to add the sync commits from the GitHub UI outside of the PR.

**Comment by AndreVuillemot160** [comment]
Oops. This is was for myself. I wilo re create the PR now.

**Pull request closed without merging**
