### PR TITLE
pulling the latest commits

### PR DESCRIPTION
**Pull request by AfoninZ**
gosh I hope the OG devs haven't broken anything

### CODE REVIEW

**Comment by Panderine** [comment]
hey! would you mind updating the  windows pre-built binaries? Also I was trying to set-up a github action for windows binaries CI but it seems quite complicated :(

**Comment by Sebastian-byte** [comment]
I've also tried to set up an Windows CI for auto build, but is almost impossible, so you can use CI for building using AppVeyor, but you must access via RDP to build properly.

**Comment by Sebastian-byte** [comment]
I will send an pull request updating the Windows binary and sending updates.

**Comment by Panderine** [comment]
I'm no github actions expert by any means, but I reached a point in my fork where I almost get it to compile. I need to figure out some of the dependencies requirements and how to install them properly on the runners. You can have a look at mine.

**Pull request merged**
